# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StackOverflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('summary', models.CharField(max_length=2000)),
                ('href', models.URLField()),
            ],
        ),
    ]
