# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stackoverflow',
            name='id',
        ),
        migrations.AlterField(
            model_name='stackoverflow',
            name='question_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
